
version: '2'
services:
    database:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wicm
            - MYSQL_USER=wicm 
            - MYSQL_PASSWORD=wicm
        restart: always
        expose: 
            - 3306
    opendaylight:
        build:
            context: ./
            dockerfile: ./odl.dockerfile
        restart: always
        ports:
            - 8080:8080
            - 6633:6633
            - 6653:6653
            - 6640:6640
            - 8181:8181
    wicm:
        build:
            context: ./
            dockerfile: ./wicm.dockerfile
        restart: always
        ports :
            - 12891:5000
        links:
            - opendaylight
            - database
        command: /opt/opendaylight/bin/karaf clean

